### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by romainthomas** [Manouchehri/frida-gadgetify#1]
https://github.com/Manouchehri/frida-gadgetify/blob/1258cbe6862b56ea995c4822ae72a602701762e3/frida-gadgetify.py#L47

It's automatically done by LIEF: https://github.com/lief-project/LIEF/blob/master/src/ELF/Builder.tcc#L615

For https://github.com/Manouchehri/frida-gadgetify/blob/1258cbe6862b56ea995c4822ae72a602701762e3/frida-gadgetify.py#L54

You can do:

```python
new_binary += lief.ELF.DynamicEntryRunPath("$ORIGIN")
# or 
new_binary += lief.ELF.DynamicEntryRunPath("/home/dave/libs/")
```
For:
https://github.com/Manouchehri/frida-gadgetify/blob/1258cbe6862b56ea995c4822ae72a602701762e3/frida-gadgetify.py#L29 
https://github.com/Manouchehri/frida-gadgetify/blob/1258cbe6862b56ea995c4822ae72a602701762e3/frida-gadgetify.py#L48

You can do:
```python
new_binary.add_library(frida_filename)
```

**Comment by Manouchehri** [comment]
1. Thanks, fixed!

2. I'll add `DynamicEntryRunPath` as an option in the future. The output is just a reminder for testing, my normal use-case is putting a single copy of `frida-gadget.so` into a standard library folder (e.g. `/lib` or inside APKs). (I also plan to add a feature to bundle Frida and an existing binary into a single executable file.)

3. `add_library` only exists for PEs it seems. =( https://lief.quarkslab.com/doc/api/python/pe.html?highlight=add_library#lief.PE.Binary.add_library

Appreciate the feedback, surprised you already found this repository.

**Comment by romainthomas** [comment]
> 3. add_library only exists for PEs it seems. =( https://lief.quarkslab.com/doc/api/python/pe.html?highlight=add_library#lief.PE.Binary.add_library

For the ``0.7.0`` yes, but I implemented it for ELF in the new version (``0.8.0`` will be released soon)

See: https://github.com/lief-project/LIEF/blob/master/api/python/ELF/objects/pyBinary.cpp#L374

**Comment by Manouchehri** [comment]
Done!

1609e31d9cde96bff5c5f07726e40e6b93694962

**Comment by Manouchehri** [comment]
Anddd pushed to master.
